# frozen_string_literal: true

require_relative 'boot'

require 'rails/all'
require_relative "../lib/custom_helpers.rb"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module OperationAnatomy
  class Application < Rails::Application
    # include RoutingHelpers

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
    config.autoload_paths += Dir["#{config.root}/lib/*"]

    config.after_initialize do 
      
      if Rails.env != "test"
        # Generate all teaching page links and asset paths. Cycle through each 
        # teaching ERB page and evaluate the template to fill in the placeholders. 
        # Links between pages are generated by the manualLink method in RoutingHelpers
        # module, located at lib/custom_helpers.rb, and asset paths are completed by
        # direct variable substitution. 
        puts "Initializing manual teaching page links"
        RoutingHelpers::preprocessManualTeachingLinks
      end 



    end 

  end
end
