# frozen_string_literal: true

require_relative 'boot'

require 'rails/all'
require_relative "../lib/custom_helpers.rb"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module OperationAnatomy
  class Application < Rails::Application
    include RoutingHelpers

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
    config.autoload_paths += Dir["#{config.root}/lib/*"]

    config.after_initialize do 

      # Generate all teaching page links and asset paths. Cycle through each 
      # teaching ERB page and evaluate the template to fill in the placeholders. 
      # Links between pages are generated by the manualLink method in RoutingHelpers
      # module, located at lib/custom_helpers.rb, and asset paths are completed by
      # direct variable substitution. 
      puts "Initializing manual teaching page links"
      Topic.all.each do |topic| 
        topic.numberOfLevels.times do |level| 
          if files = Dir["teaching/#{topic.shortName}/#{topic.levelName(level)}/*.erb"]
            files.each do |f|
              begin 
                rawStr = File.read(f)
                template = ERB.new(rawStr)
                flatHTMLString = template.result(binding)
                f['.erb'] = ''
                File.open(f, 'w') { |nf| nf << flatHTMLString }
              rescue Exception => e 
                puts "Error on page #{f}"
                puts e.to_s 
                raise "ManualLinkError"
              end 
            end 
          end  
        end 
      end 



    end 

  end
end
