# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   topic = Topic.create([{ name: 'Shoulder' }])
#   Question.create(body: 'A question', topic: topic.first)

# delete all objects (note that questions depend on topic so will be destroyed)
User.delete_all
Topic.delete_all


User.create!(email: "tomfrankkirk@gmail.com", password: "password")
shoulderTopic = Topic.create(name: "Shoulder")

shoulderTopic.questions << Question.create(number: 1, level: 1, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])
shoulderTopic.questions << Question.create(number: 2, level: 1, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])
shoulderTopic.questions << Question.create(number: 3, level: 1, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])

shoulderTopic.questions << Question.create(number: 1, level: 2, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])
shoulderTopic.questions << Question.create(number: 2, level: 2, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])
shoulderTopic.questions << Question.create(number: 3, level: 2, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])

shoulderTopic.questions << Question.create(number: 1, level: 3, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])
shoulderTopic.questions << Question.create(number: 2, level: 3, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])
shoulderTopic.questions << Question.create(number: 3, level: 3, body: "Choose the right answer", solution: "Right", possibleSolutions: ["Right", "Wrong"])




# Seed the dictionary definitions. Correct as of 6 March 2017. 

DictionaryEntry.create(title: "-poiesis", definition: "relating to making/formation.", example: "Haematopoiesis is the process of making all types of blood cells.")
DictionaryEntry.create(title: "abduction", definition: "movement of a limb away from the midline of the body.", example: "")
DictionaryEntry.create(title: "accessory", definition: "additional, supplementary, subsidiary to the main structure.", example: "An accessory digestive organ, such as the pancreas, is an organ that helps with digestion but is not part of the digestive tract.")
DictionaryEntry.create(title: "acinus", definition: "cluster of cells/structures forming a structure resembling a berry.", example: "The respiratory bronchioles of the lungs terminate in acini, which are multi-lobed sacs containing groups of alveoli.")
DictionaryEntry.create(title: "adduction", definition: "movement of a limb towards the midline of the body.", example: "")
DictionaryEntry.create(title: "adenoid", definition: "most superior member of the tonsils of the throat.", example: "")
DictionaryEntry.create(title: "adluminal", definition: "near or towards the lumen of a structure.", example: "Maturation of the male gametes within the seminiferous tubules occurs in an adluminal direction, from the outermost immature spermatogonia to the innermost spermatids and spermatozoa.")
DictionaryEntry.create(title: "adventitia", definition: "outermost connective tissue covering an organ or vessel.", example: "The tunica adventitia is the outermost layer of the walls of blood vessels, surrounding the tunica media.")
DictionaryEntry.create(title: "afferent", definition: "a structure carrying information or substances inwards to an organ.", example: "The afferent arterioles of the kidney connect the renal artery to the glomerular capillary network.")
DictionaryEntry.create(title: "agonist", definition: "the agonist in a movement is the muscle or muscles that provide the major force to complete the movement. Also known as prime movers.", example: "The biceps brachii is the agonist of elbow flexion.")
DictionaryEntry.create(title: "albicans", definition: "white or whitish.", example: "The corpus albicans is the remnant structure of the corpus luteum.")
DictionaryEntry.create(title: "alimentary", definition: "relating to nutrition and the organs of digestion.", example: "The alimentary canal includes the mouth, pharynx, oesophagus, stomach, small intestine, large intestine and anus.")
DictionaryEntry.create(title: "alpha cell", definition: "glucagon producing cells of the pancreatic islets of Langerhans.", example: "")
DictionaryEntry.create(title: "alveolus", definition: "a small cavity or pit.", example: "The alveoli of the lungs are the small air-filled sacs where gaseous exchange occurs.")
DictionaryEntry.create(title: "amnion", definition: "the innermost layer of the embryonic membranes, which contains amniotic fluid in which the foetus is suspended.", example: "")
DictionaryEntry.create(title: "ampulla", definition: "a small dilatation in a canal or duct.", example: "The ampulla of Vater is an enlargement at the point of confluence between the common bile duct and pancreatic ducts just proximal to their entrance into the duodenum.")
DictionaryEntry.create(title: "anastomosis", definition: "a connection between structures that are normally separated. May be physiological, created surgically or pathological.", example: "The Circle of Willis at the base of the brain is an arterial anastomosis that connects the carotid circulation with the vertebral circulation.")
DictionaryEntry.create(title: "antagonist", definition: "the antagonist in a movement refers to the muscles that oppose the agonist.", example: "The triceps brachii is the antagonist of elbow flexion.")
DictionaryEntry.create(title: "anterior", definition: "the front surface of the body.", example: "The umbilicus is on the anterior aspect of the abdomen.")
DictionaryEntry.create(title: "antrum", definition: "an anatomical cavity contained within a hollow organ or within a bone.", example: "The antrum of the stomach is located in the lower part of the stomach, between the body and the pyloric canal.")
DictionaryEntry.create(title: "anulus", definition: "a structure resembling a ring.", example: "The anulus fibrosus is the fibrous structure that surrounds the nucleus pulposus of the vertebral disc, resisting its herniation.")
DictionaryEntry.create(title: "aorta", definition: "the largest artery in the body, arising from the outflow tract of the left ventricle.", example: "")
DictionaryEntry.create(title: "apical", definition: "relating to the apex/tip of a pyramidal structure.", example: "An apical lung tumour, located in the lung apices, can press on the sympathetic chain in the neck to cause Horner's syndrome.")
DictionaryEntry.create(title: "apocrine", definition: "a type of glandular secretion where the apical portion of secretory cells is released into the secretion.", example: "The mammary glands are apocrine glands since lipid-rich droplets enveloped by the apical cell membranes are released into the secretion.")
DictionaryEntry.create(title: "aponeurosis", definition: "a sheetlike fibrous membrane formed of dense connective tissue, that functions to bind muscles together and act as broad, flat tendons.", example: "The biceps brachii inserts distally into both the radial tuberosity and the bicipital aponeurosis on the medial aspect of the forearm.")
DictionaryEntry.create(title: "appendicular skeleton", definition: "the articulated bones of the upper and lower limbs.", example: "")
DictionaryEntry.create(title: "appendix testis", definition: "a vestigial remnant of the Mullerian duct of gestation.", example: "")
DictionaryEntry.create(title: "appendix vermiformis", definition: "a blind-ending pouch connected to the caecum.", example: "")
DictionaryEntry.create(title: "apposition", definition: "placing together or bringing into proximity.", example: "Appositional bone growth involves the deposition of new bone layers on those already present.")
DictionaryEntry.create(title: "aqueous humor", definition: "the transparent fluid containing low protein in the anterior and posterior chambers of the eye, functioning to nourish the lens and cornea.", example: "")
DictionaryEntry.create(title: "arachnoid", definition: "spider-like.", example: "The arachnoid membrane is the middle, delicate membrane of the meninges between the dura mater and pia mater.")
DictionaryEntry.create(title: "arachnoid granulations", definition: "small protrusions of the arachnoid membrane into the dura mater and venous sinuses.", example: "")
DictionaryEntry.create(title: "areola", definition: "a small circular area with different histology from the surrounding region.", example: "The areola of the breast is the ring of pigmented skin surrounding the nipple.")
DictionaryEntry.create(title: "arteriole", definition: "a small branch of an artery that conveys blood to capillary beds.", example: "")
DictionaryEntry.create(title: "artery", definition: "any form of blood vessel that carries oxygenated blood away from the heart to the peripheral tissues.", example: "The aorta is the largest artery of the human body.")
DictionaryEntry.create(title: "articular", definition: "relating to a joint or joints.", example: "Articular cartilage is the highly specialised cartilage of synovial joints that acts as a smooth, lubricated surface allowing bones of the joint to glide over each other with minimal friction.")
DictionaryEntry.create(title: "arytenoid", definition: "relating to the two small cartilages sat on the cricoid cartilage within the larynx.", example: "The arytenoid muscle is a single muscle passing between the two arytenoid cartilages of the larynx and functions to close the opening of the glottis.")
DictionaryEntry.create(title: "atlanto-", definition: "relating to the atlas (C1, vertebra that supports the cranium).", example: "The atlanto-occipital joint is a pair of condyloid joints between the atlas and the occipital bone of the skull.")
DictionaryEntry.create(title: "atresia", definition: "Absence or closure of a natural passage of the body .", example: "Oesophageal atresia is a birth defect in which the oesophagus is a blind ending tube.")
DictionaryEntry.create(title: "atrophy", definition: "the decreaase in size of an organ or tissue.", example: "Thymic atrophy, also known as involution, occurs as part of normal development beginning in early childhood.")
DictionaryEntry.create(title: "Auerbach's plexus", definition: "also known as the myenteric plexus, located between the longitudinal and circular muscle layers of the intestine and supplies motor innervation to both muscle layers.", example: "")
DictionaryEntry.create(title: "autonomic", definition: "occurring involuntarily, relating to the autonomic nervous system.", example: "Autonomic functions include regulation of heart rate, respiratory rate, digestion and the pupillary reflex.")
DictionaryEntry.create(title: "axial skeleton", definition: "the bones of the head and trunk.", example: "")
DictionaryEntry.create(title: "axillary", definition: "relating to the armpit region, at the junction of the arm and the thorax.", example: "The axillary artery is a large vessel arising from the subclavian artery and is the major artery supplying the upper limb.")
DictionaryEntry.create(title: "azygos", definition: "an unpaired anatomical structure.", example: "The azygos vein is an unpaired vein transporting deoxygenated blood from the posterior walls of the thorax and abdomen into the superior vena cava.")
DictionaryEntry.create(title: "basal lamina", definition: "a layer of the basement membrane lying immediately adjacent to the basal surface of the adjoining cell layer.", example: "")
DictionaryEntry.create(title: "basement membrane", definition: "a thin, fibrous, extracellular matrix of tissue separating a layer of epitherlial cells from the underlying layers of tissue.", example: "")
DictionaryEntry.create(title: "beta cell", definition: "insulin producing cells of the pancreatic islets of Langerhans.", example: "")
DictionaryEntry.create(title: "biceps", definition: "a two-headed muscle.", example: "There are two flexor muscles in the body that are referred to as")
DictionaryEntry.create(title: "bicuspid", definition: "as having or terminating in two cusps or points.", example: "The bicuspid valve, also known as the mitral valve, has two cusps and is located between the left atrium and left ventricle.")
DictionaryEntry.create(title: "brachio-", definition: "relating to the arm.", example: "The brachial artery is the major arterial supply to the upper arm.")
DictionaryEntry.create(title: "brevis", definition: "short.", example: "Adductor brevis is a relatively short muscle on the medial aspect of the thigh that contributes to hip adduction.")
DictionaryEntry.create(title: "bronchiole", definition: "a passageway through which air passes from the bronchi into the alveoli of the lungs.", example: "")
DictionaryEntry.create(title: "bronchus", definition: "a passageway through which air passes from the trachea into the bronchioles of the lungs.", example: "")
DictionaryEntry.create(title: "brush border", definition: "a specialisation of the free surface of a cell, consisting of a dense array of microvilli, functioning to maximise surface area.", example: "The apical surfaces of the epithelium of the small intestine form a brush border due to the presence of microvilli, to maximise surface area available for absorption.")
DictionaryEntry.create(title: "buccal", definition: "relating to the mouth or cheek.", example: "The buccal cavity, also known as the oral cavity, is the first portion of the alimentary tract.")
DictionaryEntry.create(title: "bulbar", definition: "relating to the medulla of the brainstem.", example: "Bulbar palsy results from pathology affecting the lower cranial nerves (VII-XII) which arise from the brainstem.")
DictionaryEntry.create(title: "bursa", definition: "a small, fluid-filled sac placed around joints in order to cushion bones from movements of muscles, tendons and skin.", example: "The suprapatella bursa, located between the anterior surface of the distal end of the femur and the deep surface of the quadriceps muscle group, allows relatively friction free movement of the tendon over the femur.")
DictionaryEntry.create(title: "calvaria", definition: "the domelike, superior portion of the cranium (skullcap).", example: "")
DictionaryEntry.create(title: "calyx", definition: "a cuplike structure.", example: "The renal calyces are chambers within the kidney that function as the beginning of the urine collecting system, passing urine to the renal pelvis for release to the bladder.")
DictionaryEntry.create(title: "capillary", definition: "the smallest blood vessels, serving to distribute oxygenated blood from arteries to the tissues and return deoxygenated blood to the veins.", example: "")
DictionaryEntry.create(title: "capitis", definition: "relating to the head.", example: "Splenius capitis is a broad muscle on the posterior aspect of the neck, assisting shaking of head movements.")
DictionaryEntry.create(title: "capitulum", definition: "a rounded prominence that articulates into another bone.", example: "The capitulum is the lateral part of the distal humerus which articulates with the head of the radius.")
DictionaryEntry.create(title: "capsule", definition: "a fibrous, membranous or fatty sac that surrounds an organ, joint or other structure.", example: "Renal capsule")
DictionaryEntry.create(title: "cardia", definition: "the region of the stomach into which the contents of the oesophagus empty, bordered by the fundus and the body of the stomach.", example: "")
DictionaryEntry.create(title: "carotid", definition: "the major arteries of the neck, supplying structures of the neck, face and the brain.", example: "")
DictionaryEntry.create(title: "carpi", definition: "relating to the wrist.", example: "flexor carpi ulnaris")
DictionaryEntry.create(title: "caudal", definition: "at or near the tail or hind parts.", example: "The coccyx is the located at the caudal end of the vertebral column.")
DictionaryEntry.create(title: "cavernous", definition: "a structure filled with cavities or hollow areas.", example: "The cavernous sinus of the skull is a dural venous sinus within the temporal and sphenoid bone that drains anterior structures of the brain.")
DictionaryEntry.create(title: "cephalic", definition: "relating to the head or the head end of the body.", example: "The blood within the venous systems of the lower limb moves in a cephalic direction due to the compression effect of surrounding muscles and the presence of valves preventing backflow.")
DictionaryEntry.create(title: "cervix", definition: "the cylinder shaped neck of tissue connecting the vagina to the uterus.", example: "")
DictionaryEntry.create(title: "chorion", definition: "the outermost layer of the foetal membranes, which develops villi and forms the placenta.", example: "")
DictionaryEntry.create(title: "circumduction", definition: "the conical movement of a body part, therefore consisting of flexion, extension, abduction and adduction movements.", example: "")
DictionaryEntry.create(title: "clavicle", definition: "also known as the collar bone, a slender, curved bone forming part of the shoulder girdle which articulates with the manubrium  of the sternum and acromion of the scapula.", example: "")
DictionaryEntry.create(title: "cleido-", definition: "relating to the clavicle.", example: "The sternocleidomastoid muscle arises from the sternum and clavicle, and inserts into the mastoid of the base of the skull.")
DictionaryEntry.create(title: "coeliac", definition: "relating to the abdominal cavity.", example: "The coeliac trunk is the first major branch of the abdominal aorta and supplies the oesophagus, stomach, liver, pancreas, spleen and parts of the duodenum.")
DictionaryEntry.create(title: "coelom", definition: "a cavity in the mesoderm of the developing embryo, giving rise to the pleural, pericardial and peritoneal cavities following gestation.", example: "")
DictionaryEntry.create(title: "collateral", definition: "EITHER (1) circulation of blood through a network of small vessels that become enlarged when a major artery or vein is compromised OR (2) an accessory or subordinate structure.", example: "The medial and lateral collateral ligaments of the knee stabilise the joint against valgus and varus forces.")
DictionaryEntry.create(title: "colon", definition: "the part of the large intestine from the caecum to the rectum.", example: "")
DictionaryEntry.create(title: "concha", definition: "resemble a spiral shell in shape.", example: "The nasal conchae (or turbinates) are long, curled shelves of bone in the nose that force inhaled air to flow in a regular pattern around the nasal cavity.")
DictionaryEntry.create(title: "condyle", definition: "a rounded prominence at the articular surface of some bones, often occurring in pairs.", example: "The medial and lateral femoral condyles form the articular surface of the distal end of the femur.")
DictionaryEntry.create(title: "conjunctiva", definition: "a thin, transparent, moist membrane that covers the front of the eye and lines the eyelids.", example: "")
DictionaryEntry.create(title: "constrictor", definition: "a muscle that contracts a cavity or compresses an organ.", example: "The superior, middle and inferior pharyngeal constrictor muscles function to contract on a bolus of food, conveying it inferiorly towards the oesophagus.")
DictionaryEntry.create(title: "coraco-", definition: "relating to the coracoid process of the scapula.", example: "The coracohumeral ligament is a broad ligament that resists inferior subluxation of the humerus and passes from the coracoid process to the margin of the greater and lesser tubercles of the humerus.")
DictionaryEntry.create(title: "cornea", definition: "the transparent, anterior section of the eye that covers the pupil and iris, functioning to refract light.", example: "")
DictionaryEntry.create(title: "cornu", definition: "a horn-shaped structure.", example: "The greater cornu is a horn-like projection of the lateral ends of the hyoid bone.")
DictionaryEntry.create(title: "corpus", definition: "the main part of an organ.", example: "The corpus cavernosum of the penis is a pair of sponge-like structures which act as the major erectile tissue during an erection.")
DictionaryEntry.create(title: "cortex", definition: "the outer layer of an organ or structure.", example: "The outer part of the kidney parenchyma is called the renal cortex.")
DictionaryEntry.create(title: "cranial", definition: "EITHER (1) relating to the cranium OR (2) towards the head.", example: "The atlas is at the cranial end of the vertebral column.")
DictionaryEntry.create(title: "crest", definition: "a ridge of a bone.", example: "The iliac crest is the ridge of bone running along the superior border of the iliac wing of the pelvis.")
DictionaryEntry.create(title: "cribriform plate", definition: "the horizontal plate of bone in the skull perforated with numerous foramina, for the passage of olfactory nerve fibres.", example: "")
DictionaryEntry.create(title: "crico-", definition: "relating to the cricoid cartilage.", example: "The cricothyroid muscle is the only tensor muscle of the larynx, which passes between the cricoid cartialge and the thyroid cartilage and causes the voice to increase in pitch on contraction. ")
DictionaryEntry.create(title: "cutaneous", definition: "relating to or affecting the skin.", example: "Cutaneous nerves provide sensory innervation to the skin as well as motor innervation to glandular structures.")
DictionaryEntry.create(title: "cyst", definition: "sac-like structures filled with liquid, semisolid or gaseous material.", example: "Patients with polycystic kidney disease (PKD) develop numerous fluid-filled cysts within the kidneys, which may ultimately lead to kidney failure.")
DictionaryEntry.create(title: "cystic", definition: "relating to the gallbladder.", example: "The gallbladder is supplied by the cystic artery, a branch of the right hepatic artery.")
DictionaryEntry.create(title: "deep", definition: "situated at a deeper level in relation to a specific reference point, typically the skin.", example: "The lungs are situated deep to the ribcage.")
DictionaryEntry.create(title: "dens", definition: "a tooth-like process extending from the axis vertebra, articulating with the atlas to allow rotation.", example: "")
DictionaryEntry.create(title: "dentate", definition: "containing teeth-like projections.", example: "The dentate (or pectinate) line is an anatomical line that  divides the upper two thirds (simple columnar epithelium) from the lower third (stratified epithelium) of the anal canal.")
DictionaryEntry.create(title: "dermis", definition: "the connective tissue layer deep to the epidermis, containing cutaneous nerves, vasculature, sweat and sebaceous glands.", example: "")
DictionaryEntry.create(title: "diaphysis", definition: "the shaft of a long bone.", example: "")
DictionaryEntry.create(title: "distal", definition: "the more distant of two or more structures.", example: "The phalanges are the most distal bones of the upper limb.")
DictionaryEntry.create(title: "diverticulum", definition: "an outpouching of a hollow organ.", example: "Meckel's diverticulum is an outpouching in the small intestine present from birth, caused by the incomplete obliteration of the vitelline duct.")
DictionaryEntry.create(title: "dorsal", definition: "relating to the back or posterior of a structure.", example: "The scapulae are located on the dorsal aspect of the thoracic cage.")
DictionaryEntry.create(title: "ductus (vas) deferens", definition: "tubular structure transporting sperm from the epididymis to the ejaculatory ducts.", example: "")
DictionaryEntry.create(title: "duodenum", definition: "the proximal, 25-38cm C shaped part of the small intestine, connecting the pylorus of the stomach with the jejunum.", example: "")
DictionaryEntry.create(title: "ectoderm", definition: "one of the three primary germ cell layers of the developing embryo, that gives rise to the nervous system, mucous membranes of the mouth and anus and the skin.", example: "")
DictionaryEntry.create(title: "efferent", definition: "a structure carrying information or substances away from an organ.", example: "The efferent arterioles of the kidney take blood away from the glomerular capillary network and play an important role in maintaining glomerular filtration rate.")
DictionaryEntry.create(title: "end artery", definition: "an artery that lacks anastomoses with other arteries, so that tissue viability cannot be maintained should end artery occlusion occur.", example: "The labyrinthine artery of the internal ear is an example of an end artery.")
DictionaryEntry.create(title: "endo-", definition: "prefix indicating within, inner or containing.", example: "The endometrium is the innermost layer of the wall of the uterus.")
DictionaryEntry.create(title: "endocardium", definition: "The innermost layer of tissue lining the chambers of the heart.", example: "")
DictionaryEntry.create(title: "endochondral", definition: "Any bone that develops within and replaces a cartilaginous template.", example: "The long bones of the body develop by endochondral ossification.")
DictionaryEntry.create(title: "endocrine", definition: "relating to hormones and the glands that secrete them into the bloodstream.", example: "The islets of Langerhans of the pancreas, which secrete glucagon and insulin into the bloodstream, are examples of endocrine glands.")
DictionaryEntry.create(title: "endoderm", definition: "the innermost layer of the three primary germ layers of the developing embryo, from which the epithelium of the respiratory and digestive tracts, as well as the liver and pancreas, are derived.", example: "")
DictionaryEntry.create(title: "endometrium", definition: "the innermost layer of the wall of the uterus.", example: "")
DictionaryEntry.create(title: "endosteum", definition: "a thin, vascular layer of connective tissue lining the inner surfaces of all bone cavities.", example: "")
DictionaryEntry.create(title: "endothelium", definition: "a layer of cells lining the serous cavities, lymphatic and blood vessels.", example: "The thin layer of endothelial cells lining the vasculature forms the innermost layer of the walls of the arteries and veins, known as the tunica intima.")
DictionaryEntry.create(title: "epi-", definition: "prefix indicating a structure on, by, around or on top of.", example: "The epicardium the innermost layer of the pericardium, closely enveloping the heart and roots of the great vessels. Also called the visceral pericardium.")
DictionaryEntry.create(title: "epicardium", definition: "the innermost layer of the pericardium, closely enveloping the heart. Also called the visceral pericardium.", example: "")
DictionaryEntry.create(title: "epicondyle", definition: "prominence of bone superior to or on a condyle of a long bone.", example: "The medial and lateral epicondyles of the humerus act as a common site of forearm flexor and extensor muscle attachment respectively.")
DictionaryEntry.create(title: "epidermis", definition: "the most superficial layer of the skin, composed predominantly of keratinized dead cells.", example: "")
DictionaryEntry.create(title: "epididymis", definition: "a coiled segment of the spermatic duct that stores maturing spermatozoa and conveys them between the testis and vas deferens when appropriate.", example: "")
DictionaryEntry.create(title: "epidural space", definition: "the area surrounding the meninges, between the dura mater and the vertebral wall, which onctains vessels and fat.", example: "")
DictionaryEntry.create(title: "epiglottis", definition: "a leaf-shaped, valve-like structure that occludes the larynx during swallowing to prevent aspiration of food.", example: "")
DictionaryEntry.create(title: "epineurium", definition: "the outermost layer of the connective tissue surrounding peripheral nerves.", example: "")
DictionaryEntry.create(title: "epiphysis", definition: "the end of a long bone, formed either entirely of cartilage or separated from the shaft by a layer of cartilage. Will ultimately unite with the shaft of the bone through further ossification.", example: "")
DictionaryEntry.create(title: "epiploic", definition: "relating to the omentum.", example: "The epiploic foramen, also known as the omental foramen, is the site of communication between the greater and lesser sac of the abdomen.")
DictionaryEntry.create(title: "epiploic appendices", definition: "small, fat-filled pouches formed of peritoneum that project from the outer layer of the colon.", example: "")
DictionaryEntry.create(title: "epithelium", definition: "a thin, cellular layer covering internal and external surfaces of the body, including the lining of the respiratory and gastrointestinal tracts, vasculature and body cavities. ", example: "The trachea and bronchi of the respiratory tract are lined by ciliated pseudostratified columnar (respiratory) epithelium.")
DictionaryEntry.create(title: "eversion", definition: "movement at the ankle so that the sole points away from the midline.", example: "")
DictionaryEntry.create(title: "exocrine", definition: "relating to the secretion of a substance through a duct.", example: "The salivary glands, sweat glands and glands of the GI tract are exocrine glands.")
DictionaryEntry.create(title: "extension", definition: "a movement in the sagittal plane, causing an increase in the angle between the bones of the limb at the joint.", example: "")
DictionaryEntry.create(title: "external rotation", definition: "turning a limb outwardly, or away from the midline of the body.", example: "")
DictionaryEntry.create(title: "facet", definition: "a smooth area of bone, usually acting as an articular surface.", example: "The facet joints are a group of plane type, synovial joints between the superior articular processes (or facets) of an inferior verterbra with the inferior articular processes of a superior vertebra.")
DictionaryEntry.create(title: "fascia", definition: "internal connective tissue, rich in collagen, that functions to enclose, stabilise, attach to and separate organs and muscles.", example: "")
DictionaryEntry.create(title: "femoris", definition: "relating to the thigh or femur.", example: "Biceps femoris is a member of the hamstring group of muscles located on the posterior aspect of the thigh, and therefore contributes to knee flexion.")
DictionaryEntry.create(title: "fimbria", definition: "fringe of tissue surrounding the ostium of the oviducts, functioning to sweep ovulated oocytes into the oviducts.", example: "")
DictionaryEntry.create(title: "flavum", definition: "yellow.", example: "The ligamenta flava are yellowish, elastic ligaments that connect the laminae of adjacent vertebrae and assist in maintaining an upright posture. ")
DictionaryEntry.create(title: "flexion", definition: "a movement in the sagittal plane, causing a decrease in the angle between the bones of the limb at the joint.", example: "")
DictionaryEntry.create(title: "foramen", definition: "an opening or passageway in bone.", example: "The foramen magnum is a large opening in the posterior cranial fossa through which the origin of the spinal cord passes.")
DictionaryEntry.create(title: "fornix", definition: "an arched structure.", example: "The vaginal fornices are the superiormost regions of the vagina, extending into anterior and posterior recesses created by the vaginal portion of the cervix.")
DictionaryEntry.create(title: "fossa", definition: "a shallow depression.", example: "The glenoid fossa is a shallow depression on the lateral aspect of the scapula that articulates with the head of the humerus to form the glenohumeral joint.")
DictionaryEntry.create(title: "fovea", definition: "a small pit.", example: "The fovea centralis is the central pit at the back of the eye, in the centre of the macula lutea, that contains closely packed cone photoreceptors and thus provides the highest visual acuity.")
DictionaryEntry.create(title: "frenulum", definition: "a small fold of mucuous membrane restricting movement of a structure.", example: "The frenulum of prepuce of penis is an elastic tissue band that connects the foreskin to the vernal mucosa of the penis.")
DictionaryEntry.create(title: "fundus", definition: "the base of an organ, or the part farthest away from its opening.", example: "Bladder, gallbladder, stomach, uterus, eye and middle ear.")
DictionaryEntry.create(title: "fusiform", definition: "spindle-shaped.", example: "Fusiform muscles, such as the biceps brachii, are cylindrically shaped muscles centrally which taper at the ends,.")
DictionaryEntry.create(title: "gastric", definition: "relating to the stomach.", example: "The gastric glands are branched, tubular glands in the mucosa of the stomach that secrete substances including hydrochloric acid and pepsin.")
DictionaryEntry.create(title: "genio-", definition: "relating to the chin.", example: "Genioglossus is a paired extrinisic muscle of the tongue passing between the mandible and the dorsum of the tongue.")
DictionaryEntry.create(title: "gingiva", definition: "the oral mucosa covering the alveolar processes of the upper and lower jaws, also called the gums.", example: "")
DictionaryEntry.create(title: "glabrous", definition: "smooth or hairless.", example: "Glabrous skin is found on the palms of the hands and soles of the feet.")
DictionaryEntry.create(title: "gland", definition: "a collection of cells specialised to synthesise and secrete substances not related to their own metabolic requirements.", example: "The adrenal gland is responsible for the synthesis and secretion of glucocorticoids, mineralocorticoids, sex steroids and catecholamines.")
DictionaryEntry.create(title: "glosso-", definition: "relating to the tongue.", example: "The glossopharyngeal nerve is the ninth paired cranial nerve and whose functions include provision of general sensory innervation and taste sensation to the posterior 1/3rd of the tongue, sensory innervation to the upper pharynx and parasympathetic innervation to the parotid gland.")
DictionaryEntry.create(title: "glottis", definition: "the vocal apparatus of the larynx, including the true vocal cords and the opening between them.", example: "")
DictionaryEntry.create(title: "gluteus", definition: "relating to the three large muscles of the buttock.", example: "Gluteus maximus is the largest of the three gluteal muscles and is the main extensor of the hip.")
DictionaryEntry.create(title: "gonad", definition: "a gamete-producing gland of the reproductive system.", example: "The testes and ovaries are both examples of gonads.")
DictionaryEntry.create(title: "gracilis", definition: "slender or thin.", example: "Gracilis is a thin, superficial muscle of the medial thigh that flexes, adducts and medially rotates the hip.")
DictionaryEntry.create(title: "gray matter", definition: "the regions of the brain and spinal cord made up predominantly of neuronal cell bodies, rather than myelinated axons.", example: "")
DictionaryEntry.create(title: "groove", definition: "an elongated depression in a bone.", example: "The bicipital groove, also known as the intertubercular sulcus, is a deep depression in the proximal humerus through which the tendon of the long head of the biceps brachii passes.")
DictionaryEntry.create(title: "gyrus", definition: "a convolution on the surface of the cerebral hemispheres.", example: "The postcentral gyrus of the parietal lobe of the brain is the location of the primary somatosensory cortex.")
DictionaryEntry.create(title: "hallucis", definition: "relating to the big toe.", example: "Flexor hallucis longus is a deep muscle of the posterior compartment of the leg that inserts into the base of the distal phalanx of the big toe (hallux), causing flexion of all joints of the big toe on contraction.")
DictionaryEntry.create(title: "haustrum", definition: "small pouches of the colon, causing a sacculated apperance.", example: "")
DictionaryEntry.create(title: "head", definition: "the proximal articular prominence of a bone which articulates with another bone.", example: "The femoral head is the most proximal part of the femur, is globular in shape and articulates with the acetabulum of the pelvis.")
DictionaryEntry.create(title: "hilum", definition: "a deep fissure of an organ where blood vessels and nerves enter or emerge.", example: "The major bronchi, pulmonary arteries and veins enter the lungs at the hila.")
DictionaryEntry.create(title: "humor", definition: "a fluid or semifluid substance.", example: "Aqueous humor is a transparent fluid secreted by the ciliary epithelium of the eye that fills the space between the cornea and the lens.")
DictionaryEntry.create(title: "hyaline", definition: "a translucent, specialised form of cartilage with a glissening appearance forming most of the foetal skeleton and covering the articulating joint surfaces of the adult.", example: "")
DictionaryEntry.create(title: "hyo-", definition: "relating to the hyoid bone.", example: "The hyoglossus muscle arises from the hyoid bone and inserts into the side of the tongue, causing tongue retraction and depression on contraction.")
DictionaryEntry.create(title: "hypodermis", definition: "a subcutaneous layer of loose connective tissue containing fat.", example: "")
DictionaryEntry.create(title: "hypophysis", definition: "the pituitary gland.", example: "")
DictionaryEntry.create(title: "ileum", definition: "the distal part of the small intestine, located between the jejunum and the caecum.", example: "")
DictionaryEntry.create(title: "ilio-", definition: "relating to the ilium of the pelvis.", example: "The iliofemoral ligament is a Y-shaped ligament passing across the anterior of the hip joint between the anterior inferior iliac spine and the intertrochanteric line of the femur.")
DictionaryEntry.create(title: "ilium", definition: "the largest, superior-most bone of the pelvis.", example: "")
DictionaryEntry.create(title: "inferior", definition: "below or towards the feet.", example: "The superior mesenteric artery arises from the abdominal aorta inferior to the coeliac trunk.")
DictionaryEntry.create(title: "infra-", definition: "prefix denoting below.", example: "The infraglenoid tubercle is a prominence of the scapula located immediately inferior to the glenoid fossa and is the site of attachment for the long head of the triceps brachii.")
DictionaryEntry.create(title: "infundibulum", definition: "a funnel-shaped structure.", example: "The infundibulum commonly refers to the stalk connecting the pituitary gland to the base of the brain (extension of the hypothalamus).")
DictionaryEntry.create(title: "integument", definition: "a structure that envelopes or covers.", example: "The integumentary system consists of the skin, hair, nails and associated exocrine glands, responsible for the protection of underlying structures from water loss and abrasion.")
DictionaryEntry.create(title: "inter-", definition: "prefix denoting between or among.", example: "Intervertebral discs are fibrocartilaginous structures located between two vertebrae and act as shock absorbers along the length of the vertebral column.")
DictionaryEntry.create(title: "internal rotation", definition: "turning a limb inwardly, or towards the midline of the body.", example: "")
DictionaryEntry.create(title: "interstitial", definition: "relating to the small spaces between tissues or parts of an organ.", example: "Interstitial fluid is the major component of extracellular fluid, bathes tissue cells and is similar in composition to blood plasma.")
DictionaryEntry.create(title: "intima", definition: "the innermost layer of an organ, particularly the lining of lymphatic and blood vessels.", example: "The tunica intima is the innermost layer of an artery or vein, made up of a single layer of endothelial cells on an elastic lamina support.")
DictionaryEntry.create(title: "intramural", definition: "located within the wall of a cavity or organ.", example: "An aortic intramural haematoma occurs as a result of bleeding into the wall of the aorta due to vasa vasorum rupture, rather than a typical tunica intima tear.")
DictionaryEntry.create(title: "invagination", definition: "an infolding of tissue into itself or into another structure.", example: "Invagination of a part of intestine into another part is known as intussusception, which is medical emergency.")
DictionaryEntry.create(title: "inversion", definition: "movement at the ankle  so that the sole points towards the midline.", example: "")
DictionaryEntry.create(title: "ischio-", definition: "relating to the ischium of the pelvis.", example: "The ischiofemoral ligament is a triangular band of fibres running posterior to the hip joint, running between the ischium and the fibrous joint capsule.")
DictionaryEntry.create(title: "Islets of Langerhans", definition: "any of the groups of granular endocrine cells located in the pancreas that synthesise and secrete insulin and glucagon.", example: "")
DictionaryEntry.create(title: "isthmus", definition: "a narrow section of tissue connecting two larger parts.", example: "The thyroid isthmus connects the lower thirds of the right and left lobes.")
DictionaryEntry.create(title: "jejunum", definition: "the second region of the small intestine, located between the duodenum and the ileum.", example: "")
DictionaryEntry.create(title: "Kupffer cell", definition: "a specialised type of macrophage located in the liver, which functions to transform haemoglobin released from destroyed erythrocytes into bile pigment. ", example: "")
DictionaryEntry.create(title: "labial", definition: "relating to a lip or labium.", example: "The labial glands are small salivary glands located between the mucous membrane and the muscles around the orifice of the mouth.")
DictionaryEntry.create(title: "labyrinth", definition: "a group of communicating cavities.", example: "The bony labyrinth is the bony outer casing of the inner ear within the temporal bone.")
DictionaryEntry.create(title: "lacrimal", definition: "relating to a group of organs concerned with the production and drainage of tears.", example: "The lacrimal glands are paired glands in the upper, outer corners of the eyes, that secrete the aqueous layer of the tear film.")
DictionaryEntry.create(title: "lactiferous", definition: "relating to the production or secretion of milk.", example: "The lactiferous ducts are a system of ducts connecting the lobules of the mammary gland to the nipple,  functioning to deliver milk to the surface of the skin.")
DictionaryEntry.create(title: "lacuna", definition: "a small cavity or pit.", example: "The lacunae in bone, located between the lamellae, are occupied by osteocytes and connect to each other via canaliculi.")
DictionaryEntry.create(title: "lamella", definition: "a thin layer or plate of tissue.", example: "The concentric circles surrounding Haversian canals (vascular networks) in the osteon of bones are called lamellae.")
DictionaryEntry.create(title: "lamina", definition: "a thin, flat structure.", example: "The vertebral laminae are plates of bone that form the posterior walls of the vertebral canal and are the point of attachment of the ligamenta flava.")
DictionaryEntry.create(title: "lateral", definition: "the aspect of the body that is farther from the midline or centre of the body.", example: "The kidneys lie lateral to the abdominal aorta and inferior vena cava.")
DictionaryEntry.create(title: "levator", definition: "a muscle that raises a limb or body part.", example: "Levator scapulae is a muscle of the back and lateral aspect of the neck that elevates the scapula on contraction.")
DictionaryEntry.create(title: "line", definition: "a long, thin, usually rough projection or ridge.", example: "The intertrochanteric line of the anterior femur passes between the greater and lesser trochanter and marks the transition between the neck and shaft of the femur.")
DictionaryEntry.create(title: "linea", definition: "a long, thin, usually rough projection or ridge.", example: "The linea aspera is a roughened ridge on the posterior surface of the femur, acting as a site of attachment for a number of muscles including gluteus maximus, vastus medialis, vastus lateralis and adductor magnus.")
DictionaryEntry.create(title: "linguae", definition: "a tongue-like structure.", example: "The frenulum linguae is a fold of mucous membrane running between the floor of the mouth to the midline of the underside of the tongue.")
DictionaryEntry.create(title: "lingual", definition: "relating to or near the tongue.", example: "The lingual nerve is a branch of the mandibular division of the trigeminal nerve that supplies general sensory innervation to the anterior 2/3rds of the tongue.")
DictionaryEntry.create(title: "lobe", definition: "a rounded projection.", example: "The right lung is separated into three lobes by two fissures (horizontal and oblique), whereas the smaller left lung has just two lobes.")
DictionaryEntry.create(title: "lumbar", definition: "relating to the five lumbar vertebrae, the discs between them and the associated region of the lower back.", example: "A lumbar puncture involves the insertion of a hollow needle into the lower part of the spine (level L3/L4) to sample CSF for diagnostic tests.")
DictionaryEntry.create(title: "lumen", definition: "the inner space of a tubular organ.", example: "Blood passes through the lumen of arteries and veins.")
DictionaryEntry.create(title: "macroscopic", definition: "the appearance of a structure without the use of a microscope. Also known as gross anatomy.", example: "The rugae (folds of the inner lining) of the stomach can been seen on macroscopic examination.")
DictionaryEntry.create(title: "malleolus", definition: "a bony projection in the shape of the head of a hammer.", example: "The inferior end of the tibia terminates as the medial malleolus at the ankle joint.")
DictionaryEntry.create(title: "mammary glands", definition: "the milk producing exocrine glands of the female, consisting of clusters of alveoli and a duct system to convey milk to the surface of the skin.", example: "")
DictionaryEntry.create(title: "matrix", definition: "the intercellular substance of a tissue.", example: "The extracellular matrix of conenctive tissue provides structural support to the surrounding cells.")
DictionaryEntry.create(title: "meatus", definition: "a body opening or passage.", example: "The external auditory meatus is the canal running from the outer ear to the tympanic membrane (eardrum).")
DictionaryEntry.create(title: "medial", definition: "the aspect of the body that is closer to the midline or centre of the body.", example: "The femoral vein is medial to the femoral artery in the femoral triangle.")
DictionaryEntry.create(title: "median", definition: "related to the midline of the body.", example: "The umbilicus is located at the median point on the anterior surface of the abdomen.")
DictionaryEntry.create(title: "mediastinum", definition: "the central compartment of the thoracic cavity containing the heart, bordered laterally by the pleural cavities.", example: "")
DictionaryEntry.create(title: "medulla", definition: "EITHER (1) the inner region of an organ or tissue OR (2) an abbreviated name for the medulla oblongata.", example: "The adrenal medulla is responsible for the synthesis and secretion of adrenaline and noradrenaline.")
DictionaryEntry.create(title: "mesangium", definition: "a central part of the renal glomerulus between the capillaries. Mesangial cells are phagocytic in function.", example: "")
DictionaryEntry.create(title: "mesentery", definition: "a membranous fold attaching an organ to a body cavity wall.", example: "The transverse mesocolon is a part of the mesentery that attaches the transverse colon to the posterior abdominal wall.")
DictionaryEntry.create(title: "mesoderm", definition: "the middle layer of the three primary germ layers of the developing embryo, from which connective tissue, bone, cartilage, muscle, blood systems and organ parenchyma develop.", example: "")
DictionaryEntry.create(title: "mesothelium", definition: "simple squamous epithelium covering the serous membranes of the body cavities.", example: "")
DictionaryEntry.create(title: "metacarpo-", definition: "relating to the metacarpal bones of the hands.", example: "The metacarpophalangeal joints (MCP) occur between the metacarpal bones and the phalanges, forming the knuckles between the hand and the fingers.")
DictionaryEntry.create(title: "mitral", definition: "relating to the left atrioventricular (bicuspid) valve.", example: "")
DictionaryEntry.create(title: "mucosa", definition: "a mucous membrane.", example: "")
DictionaryEntry.create(title: "myelin", definition: "a fatty substance forming an insulating sheath around axons of nerve fibres.", example: "")
DictionaryEntry.create(title: "myo-", definition: "relating to muscle.", example: "The myocardium is the middle and thickest layer of the heart wall, composed of cardiac muscle.")
DictionaryEntry.create(title: "myocardium", definition: "the middle and thickest layer of the heart wall, composed of cardiac muscle.", example: "")
DictionaryEntry.create(title: "myoepithelium", definition: "modified, contractile epithelial cells present in some glands, such as the mammary glands, to expel exocrine secretions.", example: "")
DictionaryEntry.create(title: "myometrium", definition: "the muscular wall of the uterus.", example: "")
DictionaryEntry.create(title: "nephron", definition: "long, convoluted tubular structures of the kidney responsible for ultrafiltration, reabsorption and urine production.", example: "")
DictionaryEntry.create(title: "notch", definition: "an indentation, usually at the edge of a bone or organ.", example: "The cardiac notch of the left lung is formed to accommodate the heart in the mediastinum.")
DictionaryEntry.create(title: "nuchal", definition: "relating to the back of the neck.", example: "The nuchal ligament extends from the external occipital protuberance, along the spinous processes of the neck to terminate at C7.")
DictionaryEntry.create(title: "nucleus pulposus", definition: "the central, gelatinous core of the intervertebral disc.", example: "")
DictionaryEntry.create(title: "oedema", definition: "the accumulation of fluid in tissue spaces of the body.", example: "")
DictionaryEntry.create(title: "opposition", definition: "movement of the thumb across the palm to touch the tips of any of the other fingers.", example: "")
DictionaryEntry.create(title: "oral", definition: "relating to the mouth.", example: "")
DictionaryEntry.create(title: "oris", definition: "relating to the mouth.", example: "Orbicularis oris is a muscle of facial expression that puckers the lips.")
DictionaryEntry.create(title: "os", definition: "an opening into a hollow organ or space.", example: "The external os is the small, depressed aperture on the rounded part of the vaginal portion of the cervix, through which the cervical cavity communicates with the vagina.")
DictionaryEntry.create(title: "ossicle", definition: "a small bone.", example: "The ossicles of the middle ear (malleus, incus and stapes) are the three smallest bones in the human body.")
DictionaryEntry.create(title: "ossification", definition: "the formation of bone or a bony substance.", example: "")
DictionaryEntry.create(title: "ovary", definition: "the female gonad, resposible for the production and release of oocytes.", example: "")
DictionaryEntry.create(title: "oviduct", definition: "also known as the salpinx, Fallopian tube or uterine tube, refers to one of the tubes leading from the external surface of the ovary to the fundus of the uterus, to convey ovulated oocytes to the uterine cavity.", example: "")
DictionaryEntry.create(title: "palate", definition: "the roof of the mouth.", example: "")
DictionaryEntry.create(title: "palato-", definition: "relating to the palate.", example: "The palatoglossus muscle, supplied by the Vagus nerve, arises from the palatine aponeurosis and inserts into the tongue, allowing the back of the tongue to be raised.")
DictionaryEntry.create(title: "palpebra", definition: "the eyelid.", example: "")
DictionaryEntry.create(title: "papilla", definition: "a small nipple-like projection or elevation.", example: "The major duodenal papilla is the opening of the pancreatic duct and common bile duct into the duodenum.")
DictionaryEntry.create(title: "papillary", definition: "relating to a papilla (a small nipple-like projection or elevation).", example: "The papillary muscles of the heart's ventricles attach to the cusps of the atrioventricular valves to prevent prolapse and regurgitation of blood back into the atria during systole.")
DictionaryEntry.create(title: "para-", definition: "prefix denoting adjacent, beside or near.", example: "The paranasal sinuses are air-filled spaces within the bones of the face, located around the nasal cavity.")
DictionaryEntry.create(title: "parathyroid", definition: "four small endocrine glands adjacent to the thyroid gland, responsible for the secretion of parathyroid hormone (PTH).", example: "")
DictionaryEntry.create(title: "parietal", definition: "EITHER (1) relating to the walls of a cavity OR (2) relating to the parietal bone.", example: "The parietal pleura lines the internal surface of the thoracic cavity, separating the pleural cavity from the mediastinum.")
DictionaryEntry.create(title: "parotid", definition: "situated near the ear, usually referring to the parotid salivary gland.", example: "")
DictionaryEntry.create(title: "pars", definition: "part or portion.", example: "The pars interarticularis is the region of the vertebra between the inferior and superior articular processes.")
DictionaryEntry.create(title: "pectinate", definition: "comb-shaped.", example: "Tpectinate muscles are ridges within the walls of the atria of the heart, so named due to their resemblance to the teeth of a comb.")
DictionaryEntry.create(title: "pectoral", definition: "relating to the breast or chest.", example: "The pectoral muscles connect the anterior chest wall with the bones of the shoulder girdle and arm.")
DictionaryEntry.create(title: "pedicle", definition: "a footlike, stemlike or stalklike part of a structure.", example: "The two pedicles of the vertebrae, which connect the vertebral body to the transverse processes, create the vertebral notches required for the formation of the intervertebral foramina due to their shape.")
DictionaryEntry.create(title: "peri-", definition: "prefix denoting around.", example: "Initial periumbilical pain, felt around the umbilicus, that subsequently radiates to the right lower quadrant of the abdomen is a classical presentation of acute appendicitis. ")
DictionaryEntry.create(title: "pericardium", definition: "the membranous sac enclosing the heart.", example: "")
DictionaryEntry.create(title: "perichondrium", definition: "the fibrous membrane covering the surface of cartilage, except at the articulating joints.", example: "")
DictionaryEntry.create(title: "perimysium", definition: "fibrous connective tissue ensheathing a bundle of muscle fibres.", example: "")
DictionaryEntry.create(title: "perineurium", definition: "fibrous connective tissue ensheathing a bundle of nerve fibres.", example: "")
DictionaryEntry.create(title: "periodontal ligament", definition: "connective tissue fibres attaching the tooth to the alveolar bone of the jaw.", example: "")
DictionaryEntry.create(title: "periosteum", definition: "the dense, fibrous membrane covering the surface of bones, acting as a site of attachment for tendons.", example: "")
DictionaryEntry.create(title: "peristalsis", definition: "successive waves of involuntary muscle contractions of the digestive tract, forcing a bolus of food distally.", example: "")
DictionaryEntry.create(title: "peritoneum", definition: "the serous membrane lining the walls of the abdominal cavity and coating the surfaces of the associated viscera.", example: "")
DictionaryEntry.create(title: "pharynx", definition: "the part of the alimentary canal located between the oral cavity and the oesophagus.", example: "")
DictionaryEntry.create(title: "pia mater", definition: "the delicate, innermost layer of the three meningeal membranes, covering the brain and spinal cord.", example: "")
DictionaryEntry.create(title: "pineal", definition: "EITHER (1) resembling a pine cone in shape OR (2) relating to the pineal gland.", example: "The pineal gland is a small, melatonin-secreting gland in the brain.")
DictionaryEntry.create(title: "pisiform", definition: "resembing a pea in size and shape.", example: "The pisiform bone is a pea-shaped bone on the medial aspect of the proximal row of carpal bones.")
DictionaryEntry.create(title: "pituitary gland", definition: "the master endocrine gland, attached to the base of the brain (hypothalamus) by the infundibulum.", example: "")
DictionaryEntry.create(title: "pleura", definition: "a thin, serous membrane lining the chest cavity and reflecting onto the surface of the lungs.", example: "")
DictionaryEntry.create(title: "plexus", definition: "a network of nerves, blood vessels or lymphatics.", example: "The brachial plexus is a network of somatic nerves located in the base of the neck, derived from C5-T1 spinal nerve roots.")
DictionaryEntry.create(title: "plica", definition: "a fold or ridge.", example: "Commonly, plicae refers to folds in synovial membrane that most commonly occur on the anteromedial aspect of the knee, which may cause pain due to knee injury or overuse.")
DictionaryEntry.create(title: "pollicis", definition: "relating to the thumb.", example: "Commonly, plicae refers to folds in synovial membrane that most commonly occur on the anteromedial aspect of the knee, which may cause pain due to knee injury or overuse.")
DictionaryEntry.create(title: "porta hepatis", definition: "a deep fissure on the inferior surface of the liver, through which the hepatic portal vein, branches of the hepatic artery and hepatic ducts (portal triad) pass. ", example: "")
DictionaryEntry.create(title: "posterior", definition: "the back surface of the body.", example: "The oesophagus passes posterior to the trachea when descending through the neck.")
DictionaryEntry.create(title: "pronation", definition: "rotation of the forearm from the anatomical position so that the palm faces backwards.", example: "")
DictionaryEntry.create(title: "protraction", definition: "a forward movement of the jaw or scapula of the shoulder.", example: "")
DictionaryEntry.create(title: "protuberance", definition: "an anatomical landmark that appears as a blunt projection or prominence.", example: "The external occipital protuberance is the site of attachment of the nuchal ligament and trapezius muscles.")
DictionaryEntry.create(title: "proximal", definition: "nearer to the point of reference, such as the midline of the body or origin of a structure.", example: "The elbow is more proximal than the wrist in the upper limb.")
DictionaryEntry.create(title: "pubo-", definition: "relating to the pubic bone.", example: "The pubofemoral ligament is a stabilising ligament of the hip joint, attaching superiorly to the superior pubic ramus and obturator crest, and inferiorly to the joint capsule.")
DictionaryEntry.create(title: "pulmonary", definition: "relating to the lungs.", example: "The pulmonary artery supplies deoxygenated blood to the alveoli of the lungs in order to exchange carbon dioxide for oxygen.")
DictionaryEntry.create(title: "pylorus", definition: "the distal part of the stomach, forming a sphincter and outflow tract into the duodenum.", example: "")
DictionaryEntry.create(title: "quadratus", definition: "a muscle that is approximately square/rectangular in shape.", example: "Quadratus lumborum is a roughly rectangular muscle in the posterior abdominal wall that functions as a lateral flexor of the vertebral column.")
DictionaryEntry.create(title: "quadriceps", definition: "having four heads.", example: "The quadriceps is a large muscle group consisting of four individual muscles on the anterior surface of the thigh that all act as knee flexors.")
DictionaryEntry.create(title: "radicle", definition: "a small, root-like structure.", example: "The smallest branches of veins or fibrils of nerves may be referred to as radicles.")
DictionaryEntry.create(title: "radio-", definition: "relating to the radius.", example: "The proximal radioulnar joint is a synovial pivot joint between the head of the radius and the ring formed by the annular ligament and radial notch of the ulna.")
DictionaryEntry.create(title: "ramification", definition: "a branch or set of branches.", example: "")
DictionaryEntry.create(title: "ramus", definition: "EITHER (1) a branch of a nerve or blood vessel OR (2) a slender protrusion from a bone that forms an angle with the main body.", example: "The ramus of the mandible is the superior, articular portion of the bone, that terminates as the coronoid process and condyloid process.")
DictionaryEntry.create(title: "rectum", definition: "the terminal part of the large intestine, extending between the sigmoid colon to the anus.", example: "")
DictionaryEntry.create(title: "renal", definition: "relating to the kidney.", example: "The renal hilum is the site of entry of the renal artery and site of exit of the renal vein and ureter from the kidney.")
DictionaryEntry.create(title: "reticular", definition: "resembling a net.", example: "Reticular connective tissue is composed of a network of fine type III collagen fibres, and is found surrounding the kidney, spleen and lymph nodes.")
DictionaryEntry.create(title: "retina", definition: "the light-sensitive membrane forming the innermost layer of the posterior wall of the eyeball.", example: "")
DictionaryEntry.create(title: "retraction", definition: "a backward movement of the jaw or scapula of the shoulder.", example: "")
DictionaryEntry.create(title: "rheumatoid", definition: "rheumatoid", example: "of the joints")
DictionaryEntry.create(title: "rostral", definition: "at, near or towards the head, particularly the front of the head (face).", example: "The frontal lobe is rostral to the occipital lobe in the brain.")
DictionaryEntry.create(title: "ruga", definition: "a fold or crease.", example: "The gastric rugae are a series of ridges on the internal surface of the stomach, permitting expansion required for assisting food digestion.")
DictionaryEntry.create(title: "sac", definition: "a pouch or pouchlike structure.", example: "The greater sac is the cavity in the abdomen inside the peritoneum but outside the lesser sac.")
DictionaryEntry.create(title: "saccule", definition: "a small sac (pouch or pouchlike structure).", example: "The saccule of the inner ear is a component of the vestibular system (otolith organ) functioning to interpret linear accelerations and motions in the sagittal plane.")
DictionaryEntry.create(title: "salpingo-", definition: "relating to the oviducts.", example: "Salpingo-oophorectomy describes the surgical removal of an oviduct and ovary.")
DictionaryEntry.create(title: "salpinx", definition: "a trumpet shaped tube, such as the Eustachian tube or oviduct.", example: "")
DictionaryEntry.create(title: "scapulo-", definition: "relating to the scapula.", example: "Scapulohumeral rhythm describes the dynamic interaction between the scapula and humerus to permit maximum movement about the shoulder joint.")
DictionaryEntry.create(title: "sclera", definition: "the white, fibrous outer coating of the eyeball, covering the entire surface except for the cornea.", example: "")
DictionaryEntry.create(title: "sebaceous", definition: "relating to sebum or fat.", example: "Sebaceous glands located within the skin produce sebum to lubricate and waterproof the skin.")
DictionaryEntry.create(title: "semi-", definition: "a prefix denoting half or partial.", example: "Semitendinosus is a thin band of muscle that is a major knee flexor and is one of the three hamstring muscles.")
DictionaryEntry.create(title: "seminal vesicle", definition: "either of a pair of tubular glands that secrete seminal fluid to nourish spermatozoa.", example: "")
DictionaryEntry.create(title: "seminiferous", definition: "containing or conveying semen.", example: "")
DictionaryEntry.create(title: "septum", definition: "a partition or membrane dividing two cavities.", example: "The interventricular septum separates the cardiac ventricles and can be divided into two parts: the superior membranous septum and inferior muscular septum.")
DictionaryEntry.create(title: "serosa", definition: "a serous membrane, lining the pericardial, pleural or peritoneal cavities.", example: "")
DictionaryEntry.create(title: "serratus", definition: "any of a number of muscles of the thorax which have the appearance of a serrated border.", example: "Serratus anterior functions to protract and stabilise the scapula against the throacic wall.")
DictionaryEntry.create(title: "serum", definition: "blood plasma from which clotting factors have been removed.", example: "")
DictionaryEntry.create(title: "sesamoid", definition: "bones or cartilages that develop within a tendon or in the capsule of a joint.", example: "The patella is a large sesamoid bone within the quadriceps tendon.")
DictionaryEntry.create(title: "sinus", definition: "EITHER (1) a channel or cavity containing venous blood OR (2) an air-filled cavity within the bones of the skull.", example: "The cavernous sinus of the skull is a dural venous sinus within the temporal and sphenoid bone that drains anterior structures of the brain.")
DictionaryEntry.create(title: "sinusoid", definition: "specialised blood vessels that replace normal capillaries in certain organs, such as the liver and spleen, which are relatively permeable. ", example: "Liver sinusoids, due to their permeability, permit the mixing of oxygen rich blood from the hepatic artery with the nutrient rich blood of the portal vein.")
DictionaryEntry.create(title: "somatic", definition: "EITHER (1) relating to the body OR (2) relating to the wall of a body cavity OR (3) relating to the part of the nervous system regulating voluntary movement OR (4) the cells of the body that are not gametes.", example: "The somatic nervous system, due to its role in voluntary control of body movements, consists of both afferent (sensory) and efferent (motor) nerves.")
DictionaryEntry.create(title: "spermatogenesis", definition: "the formation and maturation of spermatozoa.", example: "")
DictionaryEntry.create(title: "sphincter", definition: "a ring of muscle surrounding an orifice of a hollow organ that may contract and relax to regulate flow through the orifice.", example: "The pyloric sphincter of the stomach regulates entry of chyme into the duodenum.")
DictionaryEntry.create(title: "spine", definition: "a projection or process likened to a thorn.", example: "The ischial spine extends from the posterior border of the ischium of the pelvis and gives attachment to the levator ani muscles.")
DictionaryEntry.create(title: "spinous", definition: "resembling a spine or thorn.", example: "The spinous process is the most posterior projection from the vertebrae and serves as a site of muscle and ligament attachment.")
DictionaryEntry.create(title: "spleen", definition: "a highly vascularised lymphatic organ located in the left upper quadrant of the abdomen, below the diaphragm, which destroys old erythrocytes, filters substances from the blood and coordinates immune responses.", example: "")
DictionaryEntry.create(title: "squamous", definition: "EITHER (1) scale-like appearance OR (2) relating to the flat part of the temporal bone.", example: "Squamous epithelium consists of thin, flat cells that creates the appearance of scales in histological sections.")
DictionaryEntry.create(title: "stellate", definition: "star-shaped, radiating from the centre.", example: "Hepatic stellate cells are pericytes found in the liver and are classically star shaped.")
DictionaryEntry.create(title: "sterno-", definition: "relating to the sternum.", example: "The sternocleidomastoid muscle arises from the sternum and clavicle, and inserts into the mastoid of the base of the skull.")
DictionaryEntry.create(title: "stomach", definition: "an enlarged sac containing gastric juices located between the oesophagus and the duodenum, which functions to store and subsequently begin food digestion.", example: "")
DictionaryEntry.create(title: "stratum", definition: "a layer of tissue.", example: "The epidermis of the skin is subdivided into five distinct strata (or layers).")
DictionaryEntry.create(title: "stylo-", definition: "relating to the styloid process of the skull.", example: "The stylomastoid foramen is located between the styloid process and mastoid process on the base of the skull.")
DictionaryEntry.create(title: "sub-", definition: "prefix denoting below.", example: "The subacromial bursa is a synovial sac located immediately below the acromion of the scapula.")
DictionaryEntry.create(title: "sulcus", definition: "a deep groove in an organ or tissue.", example: "The central sulcus of the cerebral cortex separates the parietal lobe from the frontal lobe.")
DictionaryEntry.create(title: "superior", definition: "situated above, higher or towards the head.", example: "The manubrium is superior to the body of the sternum.")
DictionaryEntry.create(title: "supination", definition: "rotation of the forearm so that the palm faces forward in the anatomical position.", example: "")
DictionaryEntry.create(title: "supra-", definition: "prefix denoting above or greater than.", example: "The supraglenoid tubercle is a rough projection immediately superior to the glenoid fossa and acts as the site of origin of the long head of the biceps brachii.")
DictionaryEntry.create(title: "suture", definition: "the line marking the junction and immovable joint between two bones.", example: "The cranial sutures are fibrous joints between the bones of the cranium which fuse shortly after birth.")
DictionaryEntry.create(title: "symphysis", definition: "EITHER (1) the growing together and joining of two, initially separate bones OR (2) the joint line formed by this joining OR (3) an articulation between bones that are united by cartilage without a synovial membrane.", example: "The pubic symphysis is the midline secondary cartilaginous joint uniting the left and right pubic bones.")
DictionaryEntry.create(title: "synarthrosis", definition: "a joint that lacks a synovial cavity and are immovable.", example: "The sutures of the skull are synarthroses.")
DictionaryEntry.create(title: "synchondrosis", definition: "a joint in which bones are fused rigidly by intervening cartilage.", example: "Two vertebrae articulating via an intervening intervertebral disc is an example of a synchondrosis.")
DictionaryEntry.create(title: "syncytium", definition: "a multinucleated mass of cytoplasm, formed from the fusion of multiple cells.", example: "Muscle fibres are an example of a syncytium, as they are formed from the fusion of multiple individual myoblasts.")
DictionaryEntry.create(title: "syndesmosis", definition: "a joint in which the bones are held together by a ligament.", example: "The joint between the fibula and the tibia at the ankle is a syndesmosis.")
DictionaryEntry.create(title: "synergist", definition: "the synergist in a movement is the muscle or muscles that stabilises a joint whilst the agonists are operating, ensuring movement occurs effectively. These muscles help to create the movement.", example: "The brachioradialis and brachialis assist biceps to create elbow flexion and are therefore synergists.")
DictionaryEntry.create(title: "synostosis", definition: "the fusion of adjacent bones.", example: "Synostosis is a normal physiological process during puberty, where the epiphyses of long bones fuse with the diaphyses.")
DictionaryEntry.create(title: "synovia", definition: "a clear, lubricating fluid secreted by the synovial membrane into the joint space.", example: "")
DictionaryEntry.create(title: "synovial membrane", definition: "a thin membrane lining the internal surface of the joint capsule and secretes synovial fluid.", example: "")
DictionaryEntry.create(title: "taenia coli", definition: "three distinct, longitudinal, ribbons of smooth muscle on the external surface of the ascending, transverse, descending and sigmoid colons.", example: "")
DictionaryEntry.create(title: "tectorial", definition: "relating to a covering.", example: "The tectorial membrane of the inner ear is a membrane immediately overlying the organ of Corti.")
DictionaryEntry.create(title: "tensor", definition: "a muscle that causes a region to become firm or tense.", example: "Tensor veli palatini is a broad muscle that contracts to tense the soft palate.")
DictionaryEntry.create(title: "teres", definition: "a shoulder muscle.", example: "Teres minor is a lateral rotator of the shoulder and is a member of the rotator cuff.")
DictionaryEntry.create(title: "thrombus", definition: "a fibrinous clot within a blood vessel or heart chamber.", example: "")
DictionaryEntry.create(title: "thryo-", definition: "relating to the thyroid or thyroid cartilage.", example: "The thyrohyoid muscle passes from the thyroid cartilage to the hyoid bone, functioning to elevate the larynx.")
DictionaryEntry.create(title: "thymus", definition: "a lymphoid organ located deep to the superior portion of the sternum, functioning as the major site of T cell selection and differentiation.", example: "")
DictionaryEntry.create(title: "thyroid", definition: "EITHER (1) the thyroid gland responsible for the production of T3 and T4 hormones OR (2) the thyroid cartilage, the largest cartilage of the larynx which forms the Adam's apple.", example: "")
DictionaryEntry.create(title: "tonsil", definition: "a small aggregate of lymphoid tissue within the oral or pharyngeal cavity walls, thought to combat respiratory infections.", example: "")
DictionaryEntry.create(title: "trabecula", definition: "EITHER (1) supporting strands of connective tissue projecting into an organ OR (2) fine spicules forming a network within cancellous bone.", example: "The trabeculae of cancellous bone provide structural support and ensures the bone is relatively light.")
DictionaryEntry.create(title: "trachea", definition: "a cartilaginous tube passing from the larynx to the bronchi, carrying air to the lungs.", example: "")
DictionaryEntry.create(title: "tract", definition: "EITHER (1) a system of organs and tissues that perform a particular function OR (2) a bundle of nerve fibres that have a common origin, termination and perform the same function.", example: "The spinothalamic tract conveys sensory information from the periphery (touch, pain and temperature) through the spinal cord to the thalamus in the brain.")
DictionaryEntry.create(title: "tragus", definition: "the skin-covered cartilaginous projection immediately in front of the meatus (opening) of the external ear.", example: "")
DictionaryEntry.create(title: "transverse", definition: "running at right angles to the long axis of the body.", example: "The muscle fibres of transversus abdominis run horizontally to insert into the linea alba at the midline.")
DictionaryEntry.create(title: "triceps", definition: "a three-headed muscle.", example: "The triceps brachii is the major elbow extensor and has three points of origin.")
DictionaryEntry.create(title: "trigeminal nerve", definition: "literally", example: "three twins")
DictionaryEntry.create(title: "trochanter", definition: "a rough bony prominence.", example: "The greater trochanter of the femur is the site of attachment of the gluteus medius muscle, a hip abductor.")
DictionaryEntry.create(title: "trochlea", definition: "a structure resembling a pulley.", example: "The trochlea of the medial humerus articulates with the trochlear notch of the ulna in the elbow joint.")
DictionaryEntry.create(title: "tubercle", definition: "a round, usually small prominence for the attachment of a tendon or ligament.", example: "The lesser tubercle of the humerus is the site of insertion of the subscapularis muscle, an internal rotator of the humerus.")
DictionaryEntry.create(title: "tuberosity", definition: "a round, usually large prominence for the attachment of a tendon or ligament.", example: "The tibial tuberosity is a large elevation of the proximal anterior surface of the tibia and serves as the insertion site of the patellar ligament.")
DictionaryEntry.create(title: "tunica", definition: "an enclosing layer of tissue.", example: "The tunica media is the middle, muscular layer of vessel walls, consisting of elastic fibres and smooth muscle cells.")
DictionaryEntry.create(title: "tympanic", definition: "relating to the middle ear or the eardrum (tympanic membrane).", example: "")
DictionaryEntry.create(title: "ultrastructure", definition: "the detailed structure of a cell or tissue that can be observed only by electron microscopy.", example: "Cellular structures such as organelles can only be examined in detail at the ultrastructural level.")
DictionaryEntry.create(title: "umbilicus", definition: "the mark on the anterior surface of the abdomen, where the umbilical cord was attached during gestation.", example: "")
DictionaryEntry.create(title: "uncus", definition: "a hook-shaped process.", example: "The uncinate process of the pancreas is a small portion of the head of the pancreas that hooks around the superior mesenteric vessels.")
DictionaryEntry.create(title: "ureter", definition: "the long duct carrying urine from the pelvis of the kidney into the urinary bladder.", example: "")
DictionaryEntry.create(title: "urethra", definition: "the duct through which urine is discharged from the bladder, and in the males, semen is discharged from the vas deferens.", example: "")
DictionaryEntry.create(title: "uvea", definition: "the vascular middle layer of the eyeball that continues anteriorly as the iris, ciliary body and choroid.", example: "")
DictionaryEntry.create(title: "uvula", definition: "the conical body of tissue projecting down from the middle of the soft palate at the back of the oral cavity.", example: "")
DictionaryEntry.create(title: "valve", definition: "a flaplike structure that ensures the one way passage of substance.", example: "The mitral valve prevents the backflow of blood from the left ventricle into the left atrium and pulmonary circulation during systole.")
DictionaryEntry.create(title: "varicosity", definition: "an enlargement or swelling.", example: "varicosity,an enlargement or swelling.")
DictionaryEntry.create(title: "vas", definition: "a vessel or duct.", example: "The vas deferens of the male transports spermatozoa from the epididymis of the testis to the ejaculatory ducts prior to ejaculation.")
DictionaryEntry.create(title: "vastus", definition: "great.", example: "The vastus medialis is a large knee extensor and member of the quadriceps muscle group located on the medial aspect of the thigh.")
DictionaryEntry.create(title: "ventral", definition: "directed towards or situated on the front of the body.", example: "The heart is ventral to the vertebral column.")
DictionaryEntry.create(title: "ventricle", definition: "a cavity or chamber.", example: "The left ventricle of the heart is responsible for collecting blood from the left atrium and expelling it into the systemic circulation.")
DictionaryEntry.create(title: "vesicle", definition: "a small sac containing fluid.", example: "The seminal vesicles are a pair of tubular glands that secrete seminal fluid to nourish spermatozoa.")
DictionaryEntry.create(title: "vestibule", definition: "a cavity at the entrance to another structure.", example: "The vestibule is the central portion of the bony labyrinth of the inner ear, between the cochlea and semicicrcular canals.")
DictionaryEntry.create(title: "villus", definition: "a vascular process from the free surface of a membrane.", example: "The small intestine mucous membrane is folded into numerous villi to maximise surface area for nutrient absorption.")
DictionaryEntry.create(title: "visceral", definition: "relating to the soft internal organs of the body (viscera).", example: "The visceral peritoneum is closely associated with the intraperitoneal organs of the abdominal cavity.")
DictionaryEntry.create(title: "vitreous", definition: "glassy.", example: "The vitreous body is a glissening gel that fills the space between the lens and retina of the eye.")
DictionaryEntry.create(title: "white matter", definition: "the regions of the brain and spinal cord made up predominantly of myelinated nerve fibres and thus makes up the conducting portion of the central nervous system.", example: "")
DictionaryEntry.create(title: "xiphoid", definition: "sword-shaped.", example: "The xiphoid process is the sword-shaped inferior termination of the sternum.")
DictionaryEntry.create(title: "zona", definition: "region or zone.", example: "The zona fasciculata is the central region of the adrenal cortex and responsible for glucocorticoid production.")
